{
 "title": "Eero Wifi Networks Stats",
 "description": "Dashboard to wuery and graph prometheus exported metrics for Eero Devices Wifi Networks.\r\n",
 "tags": [
  "wifi",
  "eero",
  "network"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "eero Wifi Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    { "expr": "eero_speed_download_mbps", "legendFormat": "Download on {{url}}" },
    { "expr": "0-eero_speed_upload_mbps", "legendFormat": "Upload on {{url}}" }
   ]
  },
  {
   "title": "Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eero_health_status", "legendFormat": "{{source}} on {{url}}" }
   ]
  },
  {
   "title": "Devices connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "devices" }
   ],
   "targets": [
    { "expr": "eero_clients_count", "legendFormat": "Devices # on {{url}}" }
   ]
  }
 ]
}